services:
  - type: web
    name: backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: dulich_db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: VNP_TMN_CODE
        sync: false
      - key: VNP_HASH_SECRET
        sync: false
      - key: VNP_URL
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNP_RETURN_URL
        value: https://weddullich.vercel.app/payment-result
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

databases:
  - name: dulich_db
    databaseName: dulich_db
    user: dulich_user
